### ISSUE TITLE
Hi, I have the same requirement as you comment on vite about add timestamp on refers.

### ISSUE THREAD

**Issue by adoin** [rubjo/rubjo#1]
Your origin common is https://github.com/vitejs/vite/issues/5825#issuecomment-1084087519
Can you provide which plugin or else you solve this? I found you marked as completed.
Thanks.

**Comment by rubjo** [comment]
Hi, the described code for `vite.config.js` in that comment worked for me in my scenario, but as @ryoji-sagara wrote in the follow-up, it might not work if you have additional imports from other JS files pointing to the same files without the timestamp.

**Comment by adoin** [comment]
> Hi, the described code for `vite.config.js` in that comment worked for me in my scenario, but as @ryoji-sagara wrote in the follow-up, it might not work if you have additional imports from other JS files pointing to the same files without the timestamp.
I see maybe more research needed.
Thanks all the same.
